Breaking bad api
bclaud/BreakingBad-API pull request #3
Opened 2021-10-13 21:58 UTC by bclaud

Fiz e refiz sem pressa algumas vezes pra entender bem a arquitetura hexagonal

Pra mim só foi um pouco dificil organizar os commits e as branchs porque eu não estava entendendo bem como as coisas se encaixavam, por isso todo o programa está só nessa branch.

Ainda faltam algumas melhorias que eu deixei em comentarios TODO

2021-10-14 08:24 UTC, gabryellr requested changes
Corrigir

2021-10-14 08:24 UTC, gabryellr commented on breakingbad/src/main/java/com/bclaud/breakingbad/configuration/BeanConfiguration.java
> +public class BeanConfiguration {
Porque esse bean?

2021-10-14 08:24 UTC, gabryellr commented on breakingbad/src/main/java/com/bclaud/breakingbad/core/models/FavPersona.java
> +public class FavPersona {
Adicione o Lombok

2021-10-14 08:24 UTC, gabryellr commented on breakingbad/src/main/java/com/bclaud/breakingbad/core/models/Persona.java
> +public class Persona {
Adicione o Lombok

2021-10-14 08:24 UTC, gabryellr commented on breakingbad/src/main/java/com/bclaud/breakingbad/core/service/PersonaUserServiceImpl.java
> +        FavPersona favPersona = new FavPersona(findById(id).get());
Aqui pode dar nullpointer se usar o get direto, a forma correta de usar o optional nesse caso é por exemplo assim:

`
findById(id)
.map(user -> mapper.toFavPersona(user))
.OrElseThrow(() -> new NotFoundException("User not found"));

`

2021-10-14 08:24 UTC, gabryellr commented on breakingbad/src/main/java/com/bclaud/breakingbad/core/service/PersonaUserServiceImpl.java
> +        favPersona.setFavorite(true);
Usa o Mapper

2021-10-14 08:24 UTC, gabryellr commented on breakingbad/src/main/java/com/bclaud/breakingbad/core/service/PersonaUserServiceImpl.java
> +        return favoritesRepository.findById(id).stream()
Acho que aqui pode dar nullpointer, testou se caso o optional estiver vazio?

2021-10-14 08:24 UTC, gabryellr commented on breakingbad/src/main/java/com/bclaud/breakingbad/core/service/PersonaUserServiceImpl.java
> +        //TODO Melhorar este codigo
concordo kkj

2021-10-14 08:24 UTC, gabryellr commented on breakingbad/src/main/java/com/bclaud/breakingbad/core/service/PersonaUserServiceImpl.java
> +        personaToPatch.setFavorite(favPersona.getFavorite());
Use o Mapstruct. Procura por @MappingStrategy do mapstruct.

https://mapstruct.org/documentation/stable/reference/html/

2021-10-14 08:24 UTC, gabryellr commented on breakingbad/src/main/java/com/bclaud/breakingbad/inboundRest/controller/PersonaController.java
> +        PersonaOutPutDto dto = personaService.findById(id).stream()
Não precisa usar stream aqui. Isso é um objeto e nao uma lista.

2021-10-14 08:24 UTC, gabryellr commented on breakingbad/src/main/java/com/bclaud/breakingbad/inboundRest/controller/PersonaController.java
> +        FavPersonaOutPutDto outPutDto = outPutMapper.favPersonaToFavPersonaOutPutDto(personaService.changeFavorite(outPutMapper.favPersonaInPutDtoToFavPersona(inPutDto)));
Quebra essas chamadas de metodo em linhas separadas, fica mais legivel

2021-10-14 21:33 UTC, bclaud commented on breakingbad/src/main/java/com/bclaud/breakingbad/configuration/BeanConfiguration.java
> +public class BeanConfiguration {
Pra nao precisar utilizar anotacoes Spring dentro do Core, no caso o @Service no PersonaUserServiceImpl

2021-10-20 20:35 UTC, bclaud commented on breakingbad/src/main/java/com/bclaud/breakingbad/core/service/PersonaUserServiceImpl.java
> +        FavPersona favPersona = new FavPersona(findById(id).get());
corrigido

2021-10-20 20:39 UTC, bclaud commented on breakingbad/src/main/java/com/bclaud/breakingbad/core/service/PersonaUserServiceImpl.java
> +        return favoritesRepository.findById(id).stream()
Realmente, nao precisava utilizar stream. removi e adicionei orElseThrow

2021-10-20 20:40 UTC, bclaud commented on breakingbad/src/main/java/com/bclaud/breakingbad/inboundRest/controller/PersonaController.java
> +        PersonaOutPutDto dto = personaService.findById(id).stream()
corrigido

2021-10-20 20:42 UTC, bclaud commented on breakingbad/src/main/java/com/bclaud/breakingbad/inboundRest/controller/PersonaController.java
> +        FavPersonaOutPutDto outPutDto = outPutMapper.favPersonaToFavPersonaOutPutDto(personaService.changeFavorite(outPutMapper.favPersonaInPutDtoToFavPersona(inPutDto)));
Quebrei mas nao ficou muito melhor kkk, esse método ta ruim, ainda não consegui pensar em uma forma melhor

2021-10-20 20:43 UTC, bclaud commented on breakingbad/src/main/java/com/bclaud/breakingbad/core/models/FavPersona.java
> +public class FavPersona {
Posso nao adicionar o Lombok? queria deixar só o Java puro dentro do core pra poder fazer laboratorio com outros frameworks depois (quarkus por exemplo)

2021-10-20 20:43 UTC, bclaud commented on breakingbad/src/main/java/com/bclaud/breakingbad/core/models/Persona.java
> +public class Persona {
Posso nao adicionar o Lombok? queria deixar só o Java puro dentro do core pra poder fazer laboratorio com outros frameworks depois (quarkus por exemplo)

2021-10-20 20:44 UTC, bclaud commented on breakingbad/src/main/java/com/bclaud/breakingbad/core/service/PersonaUserServiceImpl.java
> +        favPersona.setFavorite(true);
mesma situação do Lombok, queria nao utilizar o mapstruct dentro do core

2021-10-27 08:20 UTC, gabryellr requested changes

2021-10-27 08:20 UTC, gabryellr commented on breakingbad/src/main/java/com/bclaud/breakingbad/core/models/FavPersona.java
> +public class FavPersona {
ok

2021-11-17 09:16 UTC, merged